added shopping cart
TarasYurkovskyi/book-shop pull request #10
Opened 2024-01-02 20:11 UTC by TarasYurkovskyi

2024-01-02 21:11 UTC, annton-shakur approved these changes
Good job!

2024-01-03 08:22 UTC, d1sam requested changes
good job, but there are some minor changes should be done!

2024-01-03 08:22 UTC, d1sam commented on src/main/java/com/example/bookstore/dto/cart/CartItemRequestDto.java
> +    @Min(value = 1)
```suggestion
    @Positive
```

2024-01-03 08:22 UTC, d1sam commented on src/main/java/com/example/bookstore/dto/cart/UpdateCartItemDto.java
> +    @Min(value = 1)
```suggestion
    @Positive
```

2024-01-03 08:22 UTC, d1sam commented on src/main/java/com/example/bookstore/repository/ShoppingCartRepository.java
> +    ShoppingCart findByEmail(String email);
```suggestion
    Optional<ShoppingCart> findByEmail(String email);
```

2024-01-03 08:22 UTC, d1sam commented on src/main/java/com/example/bookstore/repository/ShoppingCartRepository.java
> +    ShoppingCart findByEmail(String email);
should return `Optional` when we write `find` method.

2024-01-03 08:22 UTC, d1sam commented on src/main/java/com/example/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        );
```suggestion
           ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(userId).orElseGet(() -> {
      ShoppingCart newShoppingCart = new ShoppingCart();
      newShoppingCart.setUser(user);
      shoppingCartRepository.save(newShoppingCart);
      return newShoppingCart;
    });
```

2024-01-03 13:35 UTC, vovasalyha approved these changes

2024-01-03 17:27 UTC, merged