added Dto, mappers, and new logic
TarasYurkovskyi/book-shop pull request #2
Opened 2023-12-06 10:34 UTC by TarasYurkovskyi

2023-12-06 13:04 UTC, AgroFix approved these changes
Good job!!!😎

2023-12-06 16:01 UTC, vovasalyha requested changes
Looks good, but see a couple of comments.

2023-12-06 16:01 UTC, vovasalyha commented on src/main/java/com/example/bookstore/repository/BookRepositoryImpl.java
> +            throw new EntityNotFoundException("Cannot save book to database: " + book, ex);
IMO this exception is not suitable for this case.

2023-12-06 16:01 UTC, vovasalyha commented on src/main/java/com/example/bookstore/repository/BookRepositoryImpl.java
> +            throw new EntityNotFoundException("Cannot find book by id from database: " + id, e);
IMO this exception is not suitable for this case.

2023-12-06 16:01 UTC, vovasalyha commented on src/main/java/com/example/bookstore/repository/BookRepositoryImpl.java
> +            throw new EntityNotFoundException("Cannot find all books from database", ex);
IMO this exception is not suitable for this case.

2023-12-06 16:01 UTC, vovasalyha commented on src/main/java/com/example/bookstore/service/BookServiceImpl.java
> +        return bookMapper
You can use Optional.map for mapping it into DTO and inline `byId` variable. It would be prettier.

2023-12-07 07:32 UTC, kshuryhin approved these changes
Looks good

2023-12-10 11:01 UTC, merged