added jwt auth
TarasYurkovskyi/book-shop pull request #8
Opened 2023-12-25 16:46 UTC by TarasYurkovskyi

2023-12-26 13:14 UTC, andrii-hoienko requested changes

2023-12-26 13:14 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/security/JwtAuthenticationFilter.java
> +            return Optional.of(bearerToken.substring(7));
magic number

2023-12-26 13:14 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Please make "Bearer " constant

2023-12-27 11:23 UTC, d1sam requested changes
Good job, but one minor change should be done!

2023-12-27 11:23 UTC, d1sam commented on src/main/java/com/example/bookstore/dto/user/UserLoginRequestDto.java
> +    @NotEmpty
```suggestion
    @NotBlank
```

2023-12-27 11:23 UTC, d1sam commented on src/main/java/com/example/bookstore/dto/user/UserLoginRequestDto.java
> +    @NotEmpty
```suggestion
    @NotBlank
```

2023-12-27 11:29 UTC, d1sam approved these changes
Well done!

2023-12-27 11:29 UTC, merged