Spring category
TarasYurkovskyi/book-shop pull request #9
Opened 2023-12-28 13:34 UTC by TarasYurkovskyi

2023-12-28 15:23 UTC, Andriy-Hrynevetskyi approved these changes
gj)

2023-12-28 15:57 UTC, d1sam requested changes
good job, but some changes should be done!

2023-12-28 15:57 UTC, d1sam commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    @PostMapping
```suggestion
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
```

2023-12-28 15:57 UTC, d1sam commented on src/main/java/com/example/bookstore/model/Category.java
> +    private String description;
```suggestion
    @Column
    private String description;
```

2023-12-28 15:57 UTC, d1sam commented on src/main/java/com/example/bookstore/model/Category.java
> +@Entity
```suggestion
@Entity
@NoArgsConstructor
```

2023-12-28 15:57 UTC, d1sam commented on src/main/resources/db/changelog/changes/12-create-categories-table.yaml
> +      author: Taras
```suggestion
      author: Taras Yurkovskiy
```

2023-12-28 15:57 UTC, d1sam commented on src/main/resources/db/changelog/changes/13-insert-categories-to-categories-table.yaml
> +      author: Taras
```suggestion
      author: Taras Yurkovskiy
```

2023-12-28 15:57 UTC, d1sam commented on src/main/resources/db/changelog/changes/14-create-books_categories-table.yaml
> +      author: Taras
```suggestion
      author: Taras Yurkovskiy
```

2023-12-28 15:57 UTC, d1sam commented on src/main/resources/application.properties
> +spring.datasource.password=*!
```suggestion
spring.datasource.password=*
```

2023-12-28 15:57 UTC, d1sam commented on src/main/resources/application.properties
> +spring.datasource.password=*!
it's unnecessary change

2023-12-28 15:57 UTC, d1sam commented on src/main/resources/db/changelog/changes/12-create-categories-table.yaml
> +                    nullable: false
you have primary key, that's why nullable constraint is unnecessary
```suggestion
```

2023-12-28 15:57 UTC, d1sam commented on src/main/resources/db/changelog/changes/14-create-books_categories-table.yaml
> +                    nullable: false
you have primary key, that's why nullable constraint is unnecessary
```suggestion
```

2023-12-28 15:57 UTC, d1sam commented on src/main/resources/db/changelog/changes/14-create-books_categories-table.yaml
> +                    nullable: false
you have primary key, that's why nullable constraint is unnecessary
```suggestion
```

2023-12-28 16:00 UTC, TarasYurkovskyi commented on src/main/resources/application.properties
> +spring.datasource.password=*!
its missclick)

2023-12-29 07:14 UTC, d1sam approved these changes
well done!

2023-12-29 07:31 UTC, merged